global:
  scrape_interval:     10s
  evaluation_interval: 10s

rule_files:
  - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: "nginx-prometheus-exporter"
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - "exporter:9113"

  - job_name: "nginx"
    metrics_path: /health
    scheme: http
    static_configs:
      - targets:
        - "frontend:80"

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - frontend:80   # Target to probe with http.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: bbox:9115  # The blackbox exporter's hostname:port.

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - alertmanager:9093
